language: swift
os: osx
osx_image: xcode9.2
xcode_workspace: ReactiveLogin.xcworkspace
xcode_scheme: ReactiveLogin
cache:
  - bundler

git:
  submodules: false

before_install:
  - make setup
  - sed -i '' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - make test-ci
