language: swift
os: osx
osx_image: xcode9.2
xcode_workspace: ReactiveLogin.xcworkspace
xocde_scheme: ReactiveLogin

git:
  submodules: false

before_install:
  - sed -i '' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
